
<?php echo $this->tag->form("players/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("players", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create players</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="team">Team</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("team", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="position">Position</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("position", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="point">Point</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("point", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="attack_point">Attack Of Point</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("attack_point", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="defense_point">Defense Of Point</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("defense_point", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
